post http://localhost:3004/api/players
Content-Type: application/json

{
"firstName": "Andre",
"lastName": "Ruotsalainen",
"email": "",
"phone": "234-987651",
"playerNr": 22,
"position": "Goalkeeper"
}
